[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
optimizer = true
optimizer_runs = 100000
#remappings = ['@openzeppelin/=lib/openzeppelin-contracts', '@chainlink/=lib/chainlink-brownie-contracts']
# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
